#CREATE DATABASE BANKSYSTEM;
USE BANKSYSTEM;

DROP TABLE IF EXISTS POSTSTED;
DROP TABLE IF EXISTS HISTORIKK_SALDO;
DROP TABLE IF EXISTS HISTORIKK_TRANSAKSJONER;
DROP TABLE IF EXISTS HISTORIKK_INNTAK;
DROP TABLE IF EXISTS HISTORIKK_UTTAK;
DROP TABLE IF EXISTS KONTOER;
DROP TABLE IF EXISTS KUNDEINFO;

CREATE TABLE KUNDEINFO (
    FØDSELSNUMMER CHAR(11) PRIMARY KEY NOT NULL,
    FORNAVN VARCHAR(255) NOT NULL,
    ETTERNAVN VARCHAR(255) NOT NULL,
    POSTNUMMER CHAR(4) NOT NULL,
    GATENAVN VARCHAR(255) NOT NULL,
    HUSNUMMER INT(255) NOT NULL,
    TELEFONNUMMER CHAR(8) NOT NULL,
    EPOSTADRESSE VARCHAR(255) NOT NULL,
    PINKODE VARCHAR(500) NOT NULL
);

CREATE TABLE KONTOER (
    KONTONUMMER INT(11) ZEROFILL AUTO_INCREMENT PRIMARY KEY NOT NULL,
    FØDSELSNUMMER CHAR(11) NOT NULL,
    SALDO FLOAT NOT NULL,
    FOREIGN KEY (FØDSELSNUMMER) REFERENCES KUNDEINFO(FØDSELSNUMMER)
);

CREATE TABLE HISTORIKK_SALDO (
    KONTONUMMER INT(11) ZEROFILL NOT NULL,
    SALDO FLOAT NOT NULL,
    TIDSPUNKT DATE,
    FOREIGN KEY (KONTONUMMER) REFERENCES KONTOER(KONTONUMMER)
);

CREATE TABLE HISTORIKK_TRANSAKSJONER (
    KONTONUMMER INT(11) ZEROFILL NOT NULL,
    SENDT_TIL_KONTONUMMER INT(11) ZEROFILL NOT NULL,
    SALDO_FØR FLOAT NOT NULL,
    SALDO_ETTER FLOAT NOT NULL,
    TRANSAKSJON_SUM FLOAT NOT NULL,
    TIDSPUNKT DATE,
    FOREIGN KEY (KONTONUMMER) REFERENCES KONTOER(KONTONUMMER)
);

CREATE TABLE HISTORIKK_INNTAK (
    KONTONUMMER INT(11) ZEROFILL NOT NULL,
    SALDO_FØR FLOAT NOT NULL,
    SALDO_ETTER FLOAT NOT NULL,
    INNTAK_SUM FLOAT NOT NULL,
    TIDSPUNKT DATE,
    FOREIGN KEY (KONTONUMMER) REFERENCES KONTOER(KONTONUMMER)
);

CREATE TABLE HISTORIKK_UTTAK (
    KONTONUMMER INT(11) ZEROFILL NOT NULL,
    SALDO_FØR FLOAT NOT NULL,
    SALDO_ETTER FLOAT NOT NULL,
    UTTAK_SUM FLOAT NOT NULL,
    TIDSPUNKT DATE,
    FOREIGN KEY (KONTONUMMER) REFERENCES KONTOER(KONTONUMMER)
);

CREATE TABLE POSTSTED (
    POSTNUMMER CHAR(4) NOT NULL,
    POSTSTED VARCHAR(255) NOT NULL
);
