from Sjekking import float_sjekk
from Sjekking import fødselsnummer_finnes
from Sjekking import kontonummer_finnes_på_fødselsnummer
from Sjekking import kontonummer_finnes
from Sjekking import kontonummer_telling
from Sjekking import pinkode_riktig
from Sjekking import poststed_finnes
from Sjekking import spesielletegn
